Repository madsgillis/AnimalAdoptionDatingApp, pull requests merged in 2024-11, with the labels that each got.

#40 added database creation code for reference
  backend/database.sql
Labels: initial set up, PR2

#39 connected animal profile database table to admin page
  backend/app.py
  backend/package-lock.json
  backend/requirements.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin-table.js
  frontend/src/components/admin.js
Labels: enhancement, PR2

#44 Updated app.py to use PyMySQL instead of Flask-MySQLdb
  backend/app.py
  backend/requirements.txt
Labels: enhancement, PR2

#42 feat: Add social features to adoption feed
  frontend/package-lock.json
  frontend/src/components/feed/AdoptionFeed.css
  frontend/src/components/feed/news-feed.js
Labels: enhancement

#52 add adoption feed filtering logic and update UI improvements
  frontend/src/components/feed/AdoptionFeed.css
  frontend/src/components/feed/adoption-post.js
  frontend/src/components/feed/news-feed.js
Labels: enhancement, PR3
