Repository madsgillis/AnimalAdoptionDatingApp, pull requests merged in 2024-10, with the labels that each got.

#10 Base admin page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin.js
Labels: enhancement

#11 Database setup
  backend/app.py
  backend/requirements.txt
Labels: initial set up

#32 Created base admin page table
  frontend/package.json
  frontend/src/components/admin-table.js
  frontend/src/components/admin.js
  frontend/src/components/images/Lily.jpg
  frontend/src/components/images/lincoln.jpg
  frontend/src/components/images/pexels-charles.jpg
  frontend/src/components/images/pexels-freddy.jpg
Labels: PR1
